### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by natewoodbridge** [simonmclean/just-news#2]
Hey! Generally looks really good. The React makes sense. If you had a GraphQL endpoint, I would suggest using Apollo Client to manage state and link the calls directly with the components, but the way you have it makes sense with a REST API.

I personally think Styled Components/Emotion would help to clean things up a lot, and would probably make it a bit more Vue like...with all parts in the same file, while still allowing you to write normal CSS (none of that CSS Object rubbish)

Below are some suggestions, but just that ... suggestions, not really things need to change.

Hope it helps!

https://github.com/simonmclean/just-news/blob/6cbdc8ec4d434175b88589e23ec18acbb5765ddd/utils/requestUtils.js#L26

You could use Axios to make life easier.

https://github.com/simonmclean/just-news/blob/6cbdc8ec4d434175b88589e23ec18acbb5765ddd/style/app.css#L1

Have you thought about using Styled Components or any CSS in JS? May make things a bit cleaner, and help keep your styles closer to the components. I know it's a matter of preference though. Also, everything becomes a component, which is nice.

https://github.com/simonmclean/just-news/blob/6cbdc8ec4d434175b88589e23ec18acbb5765ddd/components/NewsApiAttribution/NewsApiAttribution.js#L4

Some people say that default exports are considered harmful... I'm not totally sold on this but I guess can't hurt.

https://github.com/simonmclean/just-news/blob/6cbdc8ec4d434175b88589e23ec18acbb5765ddd/components/categories/CategoryNav.js#L23

The other nice things about styled-components is that can clean this up, it's also more semantic.

https://github.com/simonmclean/just-news/blob/6cbdc8ec4d434175b88589e23ec18acbb5765ddd/components/settings/ImagesToggle/ImagesToggle.js#L17

Probably overkill, but could use something like Formik to manage to state of the forms. But probably only need if fair amount of forms.

https://github.com/simonmclean/just-news/blob/6cbdc8ec4d434175b88589e23ec18acbb5765ddd/components/settings/Settings.js#L7

For these simple functional components, you could probably do an implicit return. Again, just style suggestions, not a big deal.

https://github.com/simonmclean/just-news/blob/6cbdc8ec4d434175b88589e23ec18acbb5765ddd/components/sources/SourcesNav.js#L10
https://github.com/simonmclean/just-news/blob/6cbdc8ec4d434175b88589e23ec18acbb5765ddd/components/stories/StoriesList/StoriesList.js#L15

This could maybe be a variable, in case it does not exist.

https://github.com/simonmclean/just-news/blob/6cbdc8ec4d434175b88589e23ec18acbb5765ddd/components/stories/StoryCard/StoryCard.js#L7

Could this function just be variable? Something like..
```
const attributionNodes = <div> ...
```

https://github.com/simonmclean/just-news/blob/6cbdc8ec4d434175b88589e23ec18acbb5765ddd/pages/_app.js#L78

You could maybe put these contexts into one single context...to separate concerns...but again, just style preference.

**Comment by simonmclean** [comment]
Thanks @natewoodbridge :) I think regarding libraries like Styled Components and Formik, I'll leave those for now, as I don't see the app expanding much beyond its current scope.


> just-news/components/stories/StoriesList/StoriesList.js
> 
> Line 15 in 6cbdc8e
>  const showImages = useContext(UserSettingsContext)[SETTINGS.SHOW_IMAGES]; 
> 
> This could maybe be a variable, in case it does not exist.

Could you clarify what you mean here?

**Comment by natewoodbridge** [comment]
Sorry!! I didn't see this – my fault!

Yes, so I was thinking this context could be undefined, and so cause an error. But looks like it's been refactored now.

How's the rest of the app going otherwise?
